# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz', '0003_auto_20170617_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
