# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz', '0004_auto_20170617_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
