# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz', '0005_auto_20170617_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='ddd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
