# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tz', '0006_ddd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ddd',
        ),
    ]
